sudo: false
arch:
 - amd64
 - ppc64le
language: C++
compiler:
    - clang++
install:
    - sh travis-build-and-test.sh
script:
    - echo 'Success. The tests are in the travis-build-and-test.sh script'
